<template>
  <div>
    <acc-header></acc-header>
<section class="banner banner-style-3">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6">
                        <div class="banner-content">
                            <span class="subtitle" data-sal="slide-up" data-sal-duration="1000" data-sal-delay="100">Revonue</span>
                            <h1 class="title" data-sal="slide-up" data-sal-duration="1000" data-sal-delay="200">Collection & Remittance Made Easy</h1>
                            <div class="btn-group" data-sal="slide-up" data-sal-duration="1000" data-sal-delay="300">
                                    <h6 class="subtitle" data-sal="slide-up" data-sal-duration="1000" data-sal-delay="200">Prepared By Nuclear Associates & Consultancy Services (NACS)</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="banner-thumbnail">
                            <div class="large-thumb" data-sal="slide-up" data-sal-duration="800" data-sal-delay="500">
                                <img class="paralax-image" src="assets/media/banner/rev-banner.png" alt="Shape">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <ul class="list-unstyled shape-group-20">
                <li class="shape shape-1" data-sal="slide-down" data-sal-duration="500" data-sal-delay="100">
                    <img src="assets/media/others/bubble-32.png" alt="Bubble">
                </li>
                <li class="shape shape-2" data-sal="slide-left" data-sal-duration="500" data-sal-delay="200">
                    <img src="assets/media/others/bubble-33.png" alt="Bubble">
                </li>
                <li class="shape shape-4" data-sal="slide-left" data-sal-duration="500" data-sal-delay="700">
                    <img src="assets/media/others/bubble-14.png" alt="Bubble">
                </li>
                <li class="shape shape-5" data-sal="slide-left" data-sal-duration="500" data-sal-delay="700">
                    <img src="assets/media/others/bubble-4.png" alt="Bubble">
                </li>
                <li class="shape shape-6" data-sal="slide-left" data-sal-duration="500" data-sal-delay="700">
                    <img src="assets/media/others/bubble-30.png" alt="Bubble">
                </li>
                <li class="shape shape-7" data-sal="slide-left" data-sal-duration="500" data-sal-delay="700">
                    <img src="assets/media/others/bubble-31.png" alt="Bubble">
                </li>
                <li class="shape shape-8 marque-images"></li>
            </ul>
        </section>
        <!--=====================================-->
        <!--=        Brand Area Start       	=-->
        <!--=====================================-->

                <section class="section section-padding bg-color-light pb--70">
            <div class="container">
                <div class="section-heading mb--90">
                    <span class="subtitle">Process</span>
                    <h2 class="title">How it works</h2>
                    <!-- <p>Our comprehensive logo design strategy ensures a perfectly crafted logo for your business.</p> -->
                </div>
                <div class="process-work" data-sal="slide-right" data-sal-duration="1000" data-sal-delay="100">
                    <div class="thumbnail paralax-image">
                        <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<lottie-player src="https://assets1.lottiefiles.com/packages/lf20_65fiagjg.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;" autoplay loop  ></lottie-player>
                    </div>
                    <div class="content">
                        <span class="subtitle">Step One</span>
                        <!-- <h3 class="title">Discover</h3> -->
                        <p>Patient Bill is generated by hospital staff</p>
                    </div>
                </div>
                <div class="process-work content-reverse" data-sal="slide-left" data-sal-duration="1000" data-sal-delay="100">
                    <div class="thumbnail paralax-image">
                        <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<lottie-player src="https://assets5.lottiefiles.com/temp/lf20_NvkH1R.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;"  loop  autoplay></lottie-player>
                    </div>
                    <div class="content">
                        <span class="subtitle">Step Two</span>
                        <!-- <h3 class="title">Prototype</h3> -->
                        <p>Patient pays hospital bills to Revonue Pay Point Agent</p>
                    </div>
                </div>
                <div class="process-work" data-sal="slide-right" data-sal-duration="1000" data-sal-delay="100">
                    <div class="thumbnail paralax-image">
                        <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<lottie-player src="https://assets7.lottiefiles.com/private_files/lf30_tigeu8d3.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;"  loop  autoplay></lottie-player>
                    </div>
                    <div class="content">
                        <span class="subtitle">Step Three</span>
                        <!-- <h3 class="title">Test</h3> -->
                        <p>Revonue Agent generates transaction and print transaction receipts</p>
                    </div>
                </div>
                <div class="process-work content-reverse" data-sal="slide-left" data-sal-duration="1000" data-sal-delay="100">
                    <div class="thumbnail paralax-image">
                        <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<lottie-player src="https://assets2.lottiefiles.com/packages/lf20_adfauj2c.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;"  loop  autoplay></lottie-player>
                    </div>
                    <div class="content">
                        <span class="subtitle">Step four</span>
                        <!-- <h3 class="title">Build</h3> -->
                        <p>Generated transaction is logged to hospital's Revonue Admin Portal</p>
                    </div>
                </div>
                <div class="process-work" data-sal="slide-right" data-sal-duration="1000" data-sal-delay="100">
                    <div class="thumbnail paralax-image">
                        <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<lottie-player src="https://assets7.lottiefiles.com/packages/lf20_pk5mpw6j.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;"  loop  autoplay></lottie-player>
                    </div>
                    <div class="content">
                        <span class="subtitle">Final Step</span>
                        <!-- <h3 class="title">Test</h3> -->
                        <p>Transactions are posted to the Hospital's EMR</p>
                    </div>
                </div>
                <div class="process-work content-reverse" data-sal="slide-left" data-sal-duration="1000" data-sal-delay="100">
                    <div class="thumbnail paralax-image">
                        <img src="assets/media/others/remita.png" alt="Thumbnail">
                    </div>
                    <div class="content">
                        <span class="subtitle">Final Step</span>
                        <!-- <h3 class="title">Build</h3> -->
                        <p>Transaction is settled to the right TSA on Remita</p>
                    </div>
                </div>

                
                
            </div>
            <ul class="shape-group-17 list-unstyled">
                <li class="shape shape-1"><img src="assets/media/others/bubble-24.png" alt="Bubble"></li>
                <li class="shape shape-2"><img src="assets/media/others/bubble-23.png" alt="Bubble"></li>
                <li class="shape shape-3"><img src="assets/media/others/line-4.png" alt="Line"></li>
                <li class="shape shape-4"><img src="assets/media/others/line-5.png" alt="Line"></li>
                <li class="shape shape-5"><img src="assets/media/others/line-4.png" alt="Line"></li>
                <li class="shape shape-6"><img src="assets/media/others/line-5.png" alt="Line"></li>
            </ul>
        </section>
                <section class="pt--250 pt_lg--200 pt_md--100 pt_sm--80 case-study-page-area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6" data-sal="slide-right" data-sal-duration="1000">
                        <div class="case-study-featured-thumb thumb-1">
                            <img class="paralax-image" src="assets/media/others/case-study-1.png" alt="Case Study">
                        </div>
                    </div>
                    <div class="col-xl-5 col-lg-6 offset-xl-1" data-sal="slide-left" data-sal-duration="1000" data-sal-delay="200">
                        <div class="case-study-featured">
                            <div class="section-heading heading-left">
                                <span class="subtitle">Core Features</span>
                                <h2 class="title">Offline & Online Transactions</h2>
                                <p>Patient bills can be processed with or without internet from a mobile phone or electronic tablet</p>
                                <!-- <a href="single-case-study.html" class="revonue-btn btn-fill-primary btn-large">Read Case Study</a> -->
                            </div>
<!-- <div class="case-study-counterup">
                                <div class="single-counterup">
                                    <h3 class="count-number">
                                        <span class="number count" data-count="15">15</span>
                                        <span class="symbol">%</span>
                                    </h3>
                                    <span class="counter-title">ROI increase</span>
                                </div>
                                <div class="single-counterup">
                                    <h3 class="count-number">
                                        <span class="number count" data-count="60">60</span>
                                        <span class="symbol">k</span>
                                    </h3>
                                    <span class="counter-title">Monthly website visits</span>
                                </div>
                            </div> -->
                        </div>
                    </div>

                    <div class="col-lg-6 offset-xl-1 order-lg-2" data-sal="slide-left" data-sal-duration="1000" data-sal-delay="200">
                        <div class="case-study-featured-thumb thumb-2">
                            <img class="paralax-image" src="assets/media/others/case-study-2.png" alt="Case Study">
                        </div>
                    </div>
                    <div class="col-lg-5 order-lg-1" data-sal="slide-right" data-sal-duration="1000">
                        <div class="case-study-featured">
                            <div class="section-heading heading-left">
                                <span class="subtitle">Core Features</span>
                                <h2 class="title">Revenue Head Management</h2>
                                <p>Hospital Services, Products & Prices Can Be Managed Seamlessly on Revonue.</p>
                                <!-- <a href="single-case-study.html" class="revonue-btn btn-fill-primary btn-large">Read Case Study</a> -->
                            </div>
<!-- <div class="case-study-counterup">
                                <div class="single-counterup">
                                    <h3 class="count-number">
                                        <span class="number count" data-count="15">15</span>
                                        <span class="symbol">%</span>
                                    </h3>
                                    <span class="counter-title">ROI increase</span>
                                </div>
                                <div class="single-counterup">
                                    <h3 class="count-number">
                                        <span class="number count" data-count="60">60</span>
                                        <span class="symbol">k</span>
                                    </h3>
                                    <span class="counter-title">Monthly website visits</span>
                                </div>
                            </div> -->
                        </div>
                    </div>

                    <div class="col-lg-6 order-lg-3" data-sal="slide-right" data-sal-duration="1000">
                        <div class="case-study-featured-thumb thumb-3">
                            <img class="paralax-image" src="assets/media/others/case-study-3.png" alt="Case Study">
                        </div>
                    </div>
                    <div class="col-lg-5 offset-xl-1 order-lg-4" data-sal="slide-left" data-sal-duration="1000" data-sal-delay="200">
                        <div class="case-study-featured">
                            <div class="section-heading heading-left">
                                <span class="subtitle">Core Features</span>
                                <h2 class="title">Business Intelligence & Reporting</h2>
                                <p>Gain actionable insights into hospital revenue distribution</p>
                                <!-- <a href="single-case-study.html" class="revonue-btn btn-fill-primary btn-large">Read Case Study</a> -->
                            </div>
<!-- <div class="case-study-counterup">
                                <div class="single-counterup">
                                    <h3 class="count-number">
                                        <span class="number count" data-count="15">15</span>
                                        <span class="symbol">%</span>
                                    </h3>
                                    <span class="counter-title">ROI increase</span>
                                </div>
                                <div class="single-counterup">
                                    <h3 class="count-number">
                                        <span class="number count" data-count="60">60</span>
                                        <span class="symbol">k</span>
                                    </h3>
                                    <span class="counter-title">Monthly website visits</span>
                                </div>
                            </div> -->
                        </div>
                    </div>

                </div>
                <div class="row">
                                        <div class="col-lg-6 offset-xl-1 order-lg-2" data-sal="slide-left" data-sal-duration="1000" data-sal-delay="200">
                        <div class="case-study-featured-thumb thumb-2">
                            <img class="paralax-image" src="assets/media/others/case-study-2.png" alt="Case Study">
                        </div>
                    </div>
                    <div class="col-lg-5 order-lg-1" data-sal="slide-right" data-sal-duration="1000">
                        <div class="case-study-featured">
                            <div class="section-heading heading-left">
                                <span class="subtitle">Core Features</span>
                                <h2 class="title">Transaction Management</h2>
                                <p>Seamlessly view transaction reports, filter and export to excel & PDF</p>
                            </div>
                        </div>
                    </div>
                                        <div class="col-lg-6 order-lg-3" data-sal="slide-right" data-sal-duration="1000">
                        <div class="case-study-featured-thumb thumb-3">
                            <img class="paralax-image" src="assets/media/others/case-study-3.png" alt="Case Study">
                        </div>
                    </div>
                    <div class="col-lg-5 offset-xl-1 order-lg-4" data-sal="slide-left" data-sal-duration="1000" data-sal-delay="200">
                        <div class="case-study-featured">
                            <div class="section-heading heading-left">
                                <span class="subtitle">Core Features</span>
                                <h2 class="title">Agent Management</h2>
                                <p>Seamlessly manage agents. View agents transactions, enable & disable agents and manage agents' wallet</p>
                            </div>
                        </div>
                    </div>



                </div>
            </div>
        </section>
                <section class="section section-padding bg-color-dark">
            <div class="container">
                <div class="section-heading heading-light-left">
                    <span class="subtitle">Revonue</span>
                    <h2 class="title">Happy MDAs Enjoying Our Services</h2>
                    <!-- <p>Design anything from simple icons to fully featured websites and applications.</p> -->
                </div>
                <div class="row">
                    <div class="col-lg-3 col-6" data-sal="slide-up" data-sal-duration="500">
                        <div class="brand-grid active">
                            <img src="assets/media/brand/brand-1.png" alt="Brand">
                        </div>
                    </div>
                    <div class="col-lg-3 col-6" data-sal="slide-up" data-sal-duration="500" data-sal-delay="100">
                        <div class="brand-grid">
                            <img src="assets/media/brand/brand-2.png" alt="Brand">
                        </div>
                    </div>
                    <div class="col-lg-3 col-6" data-sal="slide-up" data-sal-duration="500" data-sal-delay="200">
                        <div class="brand-grid">
                            <img src="assets/media/brand/brand-3.png" alt="Brand">
                        </div>
                    </div>
                    <div class="col-lg-3 col-6" data-sal="slide-up" data-sal-duration="500" data-sal-delay="300">
                        <div class="brand-grid">
                            <img src="assets/media/brand/brand-4.png" alt="Brand">
                        </div>
                    </div>
                    <div class="col-lg-3 col-6" data-sal="slide-up" data-sal-duration="500" data-sal-delay="400">
                        <div class="brand-grid">
                            <img src="assets/media/brand/brand-5.png" alt="Brand">
                        </div>
                    </div>
                    <div class="col-lg-3 col-6" data-sal="slide-up" data-sal-duration="500" data-sal-delay="500">
                        <div class="brand-grid">
                            <img src="assets/media/brand/brand-6.png" alt="Brand">
                        </div>
                    </div>
                    <div class="col-lg-3 col-6" data-sal="slide-up" data-sal-duration="500" data-sal-delay="600">
                        <div class="brand-grid">
                            <img src="assets/media/brand/brand-7.png" alt="Brand">
                        </div>
                    </div>
                    <div class="col-lg-3 col-6" data-sal="slide-up" data-sal-duration="500" data-sal-delay="700">
                        <div class="brand-grid">
                            <img src="assets/media/brand/brand-8.png" alt="Brand">
                        </div>
                    </div>
                </div>
            </div>
            <ul class="list-unstyled shape-group-10">
                <li class="shape shape-1"><img src="assets/media/others/line-9.png" alt="Circle"></li>
            </ul>
        </section>
                <!--=====================================-->
        <!--=      About  Quality Area Start    =-->
        <!--=====================================-->
        <section class="section section-padding bg-color-dark pb--80 pb_lg--40 pb_md--20">
            <div class="container">
                <div class="section-heading heading-light-left mb--100">
                    <!-- <span class="subtitle">Our Valus</span> -->
                    <h2 class="title">Why MDAs Need Revonue</h2>
                    <p class="opacity-50"></p>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="about-quality active">
                            <h3 class="sl-number">1</h3>
                            <!-- <h5 class="title">Exceed clients’ and colleagues’ expectations</h5> -->
                            <p>We are the foremost Partner and Agent of System Spec Limited and very conversant with the operation of the REMITA platform & Other revenue collection platforms approved by the Federal Government ofNigeria.</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="about-quality">
                            <h3 class="sl-number">2</h3>
                            <!-- <h5 class="title">Take ownership and question the status quo in a constructive manner</h5> -->
                            <p>We have weathered the vagaries and understand all the challenges that come with the Remita platform and any other revenue collection platforms of this nature.</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="about-quality">
                            <h3 class="sl-number">3</h3>
                            <!-- <h5 class="title">Be brave, curious and experiment – learn from all successes and failures</h5> -->
                            <p>We have helped all the MDAs using our services to improve their IGR.</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="about-quality">
                            <h3 class="sl-number">4</h3>
                            <!-- <h5 class="title">Act in a way that makes all of us proud</h5> -->
                            <p>We operate a front-end offline application that has allowed us to operate without delay or interference 24/7 and in any environment.</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="about-quality">
                            <h3 class="sl-number">5</h3>
                            <!-- <h5 class="title">Build an inclusive, transparent and socially responsible culture</h5> -->
                            <p>We are equipped to collect revenue in remote and rural areas with no light or internet with our offline revenue collection application and will automatically move funds collected to your TSA with CBN through our modem.</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="about-quality">
                            <h3 class="sl-number">6</h3>
                            <!-- <h5 class="title">Build an inclusive, transparent and socially responsible culture</h5> -->
                            <p>We deploy well-trained and courteous staff to mount and manage your entire revenue collection units/payment points.</p>
                        </div>
                    </div>
                                        <div class="col-lg-4">
                        <div class="about-quality">
                            <h3 class="sl-number">7</h3>
                            <!-- <h5 class="title">Build an inclusive, transparent and socially responsible culture</h5> -->
                            <p>We understand the specific needs of all payers and are meeting the desired needs providing peace of mind through ease of payment.</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="about-quality">
                            <h3 class="sl-number">8</h3>
                            <!-- <h5 class="title">Build an inclusive, transparent and socially responsible culture</h5> -->
                            <p>We also provide a fully automated Hospital Management Solution,the EMR (Electronic Medical Record). The EMR services are however priced and billed to the hospital separately after due consideration and agreement.</p>
                        </div>
                    </div>
                </div>
            </div>
            <ul class="list-unstyled shape-group-10">
                <li class="shape shape-1"><img src="assets/media/others/circle-1.png" alt="Circle"></li>
                <li class="shape shape-2"><img src="assets/media/others/line-3.png" alt="Circle"></li>
                <li class="shape shape-3"><img src="assets/media/others/bubble-5.png" alt="Circle"></li>
            </ul>
        </section>
        <!--=====================================-->
        <!--=        Contact Area Start       	=-->
        <!--=====================================-->
        <section class="section-padding bg-color-dark">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6" data-sal="slide-up" data-sal-duration="1000">
                        <div class="contact-address mb--30">
                            <div class="section-heading heading-light-left">
                                <span class="subtitle">Need a designer?</span>
                                <h2 class="title">Let’s work together</h2>
                            </div>
                            <div class="address-list">
                                <div class="address">
                                    <h6 class="title">Mail</h6>
                                    <p><a href="mailto:example@gmail.com">example@gmail.com</a></p>
                                </div>
                                <div class="address">
                                    <h6 class="title">Address</h6>
                                    <p>Warnwe Park Streetperrine, FL 33157 New York City</p>
                                </div>
                                <div class="address">
                                    <h6 class="title">Phone</h6>
                                    <p><a href="tel:+0123456789">+0123456789</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6" data-sal="slide-up" data-sal-duration="1000" data-sal-delay="200">
                        <div class="contact-form-box mb--30">
                            <h3 class="title">Describe your project</h3>
                            <form method="POST" action="mail.php" class="revonue-contact-form">
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" class="form-control" name="contact-name" placeholder="John Smith">
                                </div>
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" class="form-control" name="contact-email" placeholder="example@mail.com">
                                </div>
                                <div class="form-group mb--40">
                                    <label>How can we help you?</label>
                                    <textarea id="message" name="contact-message"  class="form-control textarea" cols="30" rows="6"></textarea>
                                </div>
                                <div class="form-group text-end">
                                    <button type="submit" class="revonue-btn btn-fill-primary w-auto btn-primary" name="submit-btn">SEND</button>
                                </div>
                                <input type="hidden" class="form-control" name="contact-company" value="Null">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
  </div>
</template>

<script>
import AccHeader from '../components/header.vue'

export default {
  components: {
    AccHeader,
  },
}

</script>
